### ISSUE TITLE
middleman-1.2.4 conflicts with middleman (~> 1.1.0) (Gem::LoadError)

### ISSUE THREAD

**Issue by pshemek** [middleman/middleman-smusher#1]
I've installed middleman-smusher and got such error when try to smush images with middleman:

```
/home/~/.rvm/gems/ruby-1.9.2-p180/gems/middleman-1.2.4/lib/middleman/server.rb:179:in `class_eval': Unable to activate middleman-smusher-0.0.2, because middleman-1.2.4 conflicts with middleman (~> 1.1.0) (Gem::LoadError)
```

**Comment by tdreyno** [comment]
Really starting to hate gem dependencies.

I just updated the middleman-smusher gem to depend on the 1.2.x series.

**Comment by thulstrup** [comment]
Does the dependency need to be updated for Middleman 2.x?

I'm seeing a similar error:
`Unable to activate middleman-smusher-0.0.3, because middleman-2.0.1 conflicts with middleman (~> 1.2.0) (Gem::LoadError)`

**Comment by tdreyno** [comment]
It does, in fact the whole extension should be updated for 2.x.

I'll open a ticket to track it.
