### ISSUE TITLE
Only smash changed files

### ISSUE THREAD

**Issue by tdreyno** [middleman/middleman-smusher#3]
Via @Sigler.

We used to do this, but the code was nasty so it was removed and nobody complained. Pretty easy to add back in. Will do it along with 3.0 support.

**Comment by kdaigle** [comment]
@tdreyno Any progress on this? I'll dig through the repo and find the code/write some code if there hasn't been. Just don't want to code to find out you already did it. :)

**Comment by tdreyno** [comment]
The initial version had this support, you can see the implementation using Marshaling:

https://github.com/middleman/middleman-smusher/commit/32c78477b45fd2a0a422306326f6e515a5d96999

I'm not sure this is the best solution. Feel free to implement this and send a pull request, hopefully we can include this with the big 3.0 release

**Comment by kdaigle** [comment]
Yeah, I found that. ETA on 3.0 release? I don't have time to work on this this weekend most likely but want to make sure I can get it in to you on time.

**Comment by tdreyno** [comment]
One more bug (https://github.com/middleman/middleman/issues/426), then pushing beta3.

Looking to get the final out June 1st.

**Comment by karlfreeman** [comment]
@tdreyno Is this considered closed due to the https://github.com/middleman/middleman/pull/436 being merged?

**Comment by tdreyno** [comment]
I don't think so.

**Comment by karlfreeman** [comment]
No worries, just wanted to clarify its status.

**Comment by the-architect** [comment]
Wouldn't the MD5 of files be enough mark them as already smushed?
If so I could take a stab at it. :)

**Comment by tlray** [comment]
This feature would be great, any news on this issue?

**Comment by tdreyno** [comment]
I would suggest everyone switch to the https://github.com/plasticine/middleman-imageoptim extension. It's much faster and it's based on a web service.
